module.exports = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  RECORD_PENDING: "RECORD_PENDING",
  CORDINATOR_PENDING: "CORDINATOR_PENDING",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  APPROVE_PENDING: "APPROVE_PENDING",
  APPROVED: "APPROVED"
};
